/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empmanagement.screens;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.table.TableCellRenderer;
import javax.swing.text.JTextComponent;

import com.employeemanagement.common.Common;
import com.employeemanagement.models.Client;
import com.employeemanagement.models.Employee;
import com.employeemanagement.models.ImageTableModel;
import com.empmanagement.persistence.IPersistence;
import com.empmanagement.persistence.Persistence;
import com.empmanagement.providers.EmployeeCategoriesForSearch;

/**
 *
 * @author arup
 */
public class AssignedEmployeeToClient extends javax.swing.JFrame {

    /**
     * Creates new form AssignedEmployeeToClient
     */
    IPersistence ip = Persistence.getInstance();
    Object data[][];
    File projectRootPath = new java.io.File("");
    String dummyImagePath = projectRootPath.getAbsolutePath()
	    + Common.getSeparator() + "src" + Common.getSeparator()
	    + "resource" + Common.getSeparator() + "image.jpg";

    public AssignedEmployeeToClient() {
	initComponents();
	initOtherComponent();
	setTitle("Assigned Employees");
	setResizable(false);
    }

    public void initOtherComponent() {

	File projectRootPath = new java.io.File("");
	List<Client> clients = null;
	clients = ip.getClients();
	client_name.setModel(new DefaultComboBoxModel(clients.toArray()));

	Client client = (Client) client_name.getSelectedItem();

	String clientID = client != null ? client.getClient_id() : "";

	List<Employee> emp = ip.getAssignedEmployeeByClient(clientID, "All");

	data = new Object[emp.size()][4];

	for (int i = 0; i < emp.size(); i++) {
	    data[i][0] = emp.get(i).getEmp_id();
	    data[i][1] = emp.get(i).getF_name().trim() + " "
		    + emp.get(i).getM_name().trim() + " "
		    + emp.get(i).getL_name().trim();
	    data[i][2] = "<html><div style='width:150px;display:inline; word-wrap: break-word;'>"
		    + emp.get(i).getAddress() + "</div></html>";

	    File file = null;

	    if (!emp.get(i).getPhoto_ID().equalsIgnoreCase("")) {
		file = new File(emp.get(i).getPhoto_ID());
	    } else {

		file = new File(dummyImagePath);
	    }

	    BufferedImage bufferedImage = null;
	    try {
		bufferedImage = ImageIO.read(file);
	    } catch (Exception e) {
		System.err.println("Error :  " + bufferedImage);
		e.printStackTrace();
	    }
	    bufferedImage = Common.resizeImage(bufferedImage, 90, 90);
	    ImageIcon icon = new ImageIcon(bufferedImage);
	    data[i][3] = icon;

	}

	String[] columnNames = { "Emp. ID", "Name", "Address", "Photo" };
	// DefaultTableModel model = new DefaultTableModel(data, columnNames);
	ImageTableModel tb = new ImageTableModel(data, columnNames);
	tbl_empdata.setModel(tb);
	tbl_empdata.setShowVerticalLines(false);
	tbl_empdata.setRowHeight(100);
	tbl_empdata.setPreferredScrollableViewportSize(tbl_empdata
		.getPreferredSize());
	tbl_empdata.setRowMargin(5);
	tbl_empdata.getColumnModel().getColumn(0).setPreferredWidth(27);
	tbl_empdata.getColumnModel().getColumn(3).setPreferredWidth(35);

	post.setModel(new DefaultComboBoxModel(EmployeeCategoriesForSearch
		.values()));

	client_name.getEditor().addActionListener(new ActionListener() {
	    @Override
	    public void actionPerformed(ActionEvent event) {

		String name = ((JTextComponent) ((JComboBox) ((Component) event
			.getSource()).getParent()).getEditor()
			.getEditorComponent()).getText();

		ip = Persistence.getInstance();
		List<Client> clients = ip.getClients(name);
		client_name.setModel(new DefaultComboBoxModel(clients.toArray()));
	    }
	});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jPanel1 = new javax.swing.JPanel();
	jPanel2 = new javax.swing.JPanel();
	jLabel2 = new javax.swing.JLabel();
	jPanel3 = new javax.swing.JPanel();
	jPanel5 = new javax.swing.JPanel();
	jPanel4 = new javax.swing.JPanel();
	client_name = new javax.swing.JComboBox();
	jLabel1 = new javax.swing.JLabel();
	search = new javax.swing.JButton();
	jLabel3 = new javax.swing.JLabel();
	post = new javax.swing.JComboBox();
	jScrollPane1 = new javax.swing.JScrollPane();
	tbl_empdata = new javax.swing.JTable() {

	    public Component prepareRenderer(TableCellRenderer renderer,
		    int row, int column) {
		Component c = super.prepareRenderer(renderer, row, column);
		if (c instanceof JComponent) {
		    if (column <= 2) {
			// X is your particlur column number

			JComponent jc = (JComponent) c;

			String text = getValueAt(row, column).toString();

			if (text.equalsIgnoreCase(""))
			    text = "NA";

			jc.setToolTipText(text);
		    }
		}
		return c;
	    }

	};

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	jPanel2.setBackground(new java.awt.Color(1, 1, 1));

	jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
	jLabel2.setForeground(new java.awt.Color(255, 255, 255));
	jLabel2.setText("Assigned Employees");

	javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
		jPanel2);
	jPanel2.setLayout(jPanel2Layout);
	jPanel2Layout
		.setHorizontalGroup(jPanel2Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 0, Short.MAX_VALUE)
			.addGroup(
				jPanel2Layout
					.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(
						jPanel2Layout
							.createSequentialGroup()
							.addContainerGap()
							.addComponent(
								jLabel2,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								455,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(205,
								Short.MAX_VALUE))));
	jPanel2Layout.setVerticalGroup(jPanel2Layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGap(0, 36, Short.MAX_VALUE)
		.addGroup(
			jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel2,
					javax.swing.GroupLayout.DEFAULT_SIZE,
					36, Short.MAX_VALUE)));

	javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
		jPanel3);
	jPanel3.setLayout(jPanel3Layout);
	jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
		Short.MAX_VALUE));
	jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 336,
		Short.MAX_VALUE));

	jPanel5.setBackground(new java.awt.Color(255, 255, 255));

	jPanel4.setBackground(new java.awt.Color(240, 255, 255));
	jPanel4.setBorder(javax.swing.BorderFactory
		.createLineBorder(new java.awt.Color(0, 0, 0)));

	client_name.setEditable(true);
	client_name.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		"Item 1", "Item 2", "Item 3", "Item 4" }));

	jLabel1.setText("Client");

	search.setText("Show");
	search.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		searchActionPerformed(evt);
	    }
	});

	jLabel3.setText("Post");

	post.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		"Item 1", "Item 2", "Item 3", "Item 4" }));

	javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
		jPanel4);
	jPanel4.setLayout(jPanel4Layout);
	jPanel4Layout
		.setHorizontalGroup(jPanel4Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel4Layout
					.createSequentialGroup()
					.addGap(16, 16, 16)
					.addComponent(
						jLabel3,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						46,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(1, 1, 1)
					.addComponent(
						post,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						139,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(18, 18, 18)
					.addComponent(
						jLabel1,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						56,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(
						client_name,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						270,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
					.addComponent(
						search,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						85,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap()));
	jPanel4Layout
		.setVerticalGroup(jPanel4Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel4Layout
					.createSequentialGroup()
					.addContainerGap()
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(
								client_name,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(search)
							.addComponent(jLabel1)
							.addComponent(jLabel3)
							.addComponent(
								post,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
					.addContainerGap(13, Short.MAX_VALUE)));

	jScrollPane1.setToolTipText("ddd");

	tbl_empdata.setAutoCreateRowSorter(true);
	tbl_empdata.setModel(new javax.swing.table.DefaultTableModel(
		new Object[][] { { null, null, null, null },
			{ null, null, null, null }, { null, null, null, null },
			{ null, null, null, null } }, new String[] { "Title 1",
			"Title 2", "Title 3", "Title 4" }));
	jScrollPane1.setViewportView(tbl_empdata);

	javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
		jPanel5);
	jPanel5.setLayout(jPanel5Layout);
	jPanel5Layout
		.setHorizontalGroup(jPanel5Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel5Layout
					.createSequentialGroup()
					.addContainerGap()
					.addGroup(
						jPanel5Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING)
							.addComponent(
								jScrollPane1)
							.addComponent(
								jPanel4,
								javax.swing.GroupLayout.Alignment.LEADING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
					.addContainerGap()));
	jPanel5Layout
		.setVerticalGroup(jPanel5Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel5Layout
					.createSequentialGroup()
					.addContainerGap()
					.addComponent(
						jPanel4,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						19, Short.MAX_VALUE)
					.addComponent(
						jScrollPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						376,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap()));

	javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
		jPanel1);
	jPanel1.setLayout(jPanel1Layout);
	jPanel1Layout
		.setHorizontalGroup(jPanel1Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel1Layout
					.createSequentialGroup()
					.addGroup(
						jPanel1Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
									.createSequentialGroup()
									.addGap(584,
										584,
										584)
									.addComponent(
										jPanel3,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
							.addGroup(
								jPanel1Layout
									.createSequentialGroup()
									.addContainerGap()
									.addComponent(
										jPanel5,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
							.addGroup(
								jPanel1Layout
									.createSequentialGroup()
									.addContainerGap()
									.addComponent(
										jPanel2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)))
					.addContainerGap()));
	jPanel1Layout
		.setVerticalGroup(jPanel1Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel1Layout
					.createSequentialGroup()
					.addComponent(
						jPanel2,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(
						jPanel5,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
					.addComponent(
						jPanel3,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap()));

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
		getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addComponent(
		jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
	layout.setVerticalGroup(layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addGroup(
		javax.swing.GroupLayout.Alignment.TRAILING,
		layout.createSequentialGroup()
			.addContainerGap()
			.addComponent(jPanel1,
				javax.swing.GroupLayout.PREFERRED_SIZE, 517,
				Short.MAX_VALUE)));

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchActionPerformed

	Client client = (Client) client_name.getSelectedItem();

	String clientID = client != null ? client.getClient_id() : "";

	String emp_Post = post.getSelectedItem().toString();

	List<Employee> emp = ip.getAssignedEmployeeByClient(clientID, emp_Post);

	Object filtereddata[][] = new Object[emp.size()][4];

	for (int i = 0; i < emp.size(); i++) {

	    filtereddata[i][0] = emp.get(i).getEmp_id();
	    filtereddata[i][1] = emp.get(i).getF_name().trim() + " "
		    + emp.get(i).getM_name().trim() + " "
		    + emp.get(i).getL_name().trim();
	    filtereddata[i][2] = emp.get(i).getAddress() != null ? emp.get(i)
		    .getAddress() : "";

	    File file = null;

	    if (!emp.get(i).getPhoto_ID().equalsIgnoreCase("")) {
		file = new File(emp.get(i).getPhoto_ID());
	    } else {

		file = new File(dummyImagePath);
	    }

	    BufferedImage bufferedImage = null;
	    try {
		bufferedImage = ImageIO.read(file);
	    } catch (Exception e) {
		e.printStackTrace();
	    }
	    bufferedImage = Common.resizeImage(bufferedImage, 90, 90);
	    ImageIcon icon = new ImageIcon(bufferedImage);

	    filtereddata[i][3] = icon;
	}

	String[] columnNames = { "Emp. ID", "Name", "Address", "Photo" };
	// DefaultTableModel model = new DefaultTableModel(data, columnNames);
	ImageTableModel tb = new ImageTableModel(filtereddata, columnNames);
	tbl_empdata.setModel(tb);

	tbl_empdata.setShowVerticalLines(false);
	tbl_empdata.setRowHeight(100);
	tbl_empdata.setPreferredScrollableViewportSize(tbl_empdata
		.getPreferredSize());
	tbl_empdata.setRowMargin(5);
	tbl_empdata.getColumnModel().getColumn(0).setPreferredWidth(27);
	tbl_empdata.getColumnModel().getColumn(3).setPreferredWidth(35);
    }// GEN-LAST:event_searchActionPerformed
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JComboBox client_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox post;
    private javax.swing.JButton search;
    private javax.swing.JTable tbl_empdata;
    // End of variables declaration//GEN-END:variables
}
