/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empmanagement.screens;

import com.employeemanagement.common.Common;
import com.employeemanagement.models.Client;
import com.employeemanagement.models.Employee;
import com.employeemanagement.utility.StringDocumentFilter;
import com.empmanagement.persistence.IPersistence;
import com.empmanagement.persistence.Persistence;
import com.empmanagement.providers.EmployeeCategories;
import static com.empmanagement.screens.EmployeeManipulationFrame.imagePath;
import static com.empmanagement.screens.EmployeeManipulationFrame.resize;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author user
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    MainFrame mainFrame;
    Client client;
    ClientListFrame listFrame;
    JFrame j = null;

    public ClientFrame(String name, MainFrame mainFrame, ClientListFrame listFrame, Client client) {

        super("Client Panel");
        initComponents();
        //setDefaultCloseOperation(JInternalFrame.EXIT_ON_CLOSE);

        this.mainFrame = mainFrame;
        this.listFrame = listFrame;
        this.client = client;

        setBounds(170, 30, 105, 70);
        setPreferredSize(new Dimension(408, 370));
        setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
        setResizable(false);
        //initOtherComponents();

        if (client != null) {
            headerText.setText("Modify Client Detail");
            btn_del.setVisible(true);
            btn_save.setVisible(false);
            btn_modify.setVisible(true);

            if (client.getClient_id() != null) {
                client_code.setText(client.getClient_id());
                client_code_panel.setVisible(true);
            }
            if (client.getClient_name() != null) {
                client_name.setText(client.getClient_name());
            }


            if (client.getClient_mob1() != null) {
                client_mob.setText(client.getClient_mob1());
            }

            if (client.getClient_mob2() != null) {
                client_phn.setText(client.getClient_mob2());
            }

            if ((client.getClient_add() != null)) {
                client_add.setText(client.getClient_add());
            }



        } else {
            initOtherComponents();
            headerText.setText("Add New Client");
            btn_del.setVisible(false);
            btn_save.setVisible(true);
            btn_modify.setVisible(false);
            client_code_panel.setVisible(false);
        }
        pack();
    }

    public void initOtherComponents() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        client_add = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        client_code_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        client_code = new javax.swing.JTextField();
        client_phn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        client_name = new javax.swing.JTextField();
        btn_modify = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        client_mob = new javax.swing.JTextField(10);
        jLabel5 = new javax.swing.JLabel();
        btn_del = new javax.swing.JButton();

        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        headerText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        headerText.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerText, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        client_add.setColumns(20);
        client_add.setRows(5);
        jScrollPane2.setViewportView(client_add);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Name");

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        client_code_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("ID");

        client_code.setEditable(false);
        client_code.setBackground(new java.awt.Color(153, 255, 255));
        client_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_codeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout client_code_panelLayout = new javax.swing.GroupLayout(client_code_panel);
        client_code_panel.setLayout(client_code_panelLayout);
        client_code_panelLayout.setHorizontalGroup(
            client_code_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_code_panelLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(client_code, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        client_code_panelLayout.setVerticalGroup(
            client_code_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(client_code_panelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(client_code_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Mob. No.");

        ((AbstractDocument) client_name.getDocument()).setDocumentFilter(new StringDocumentFilter());

        btn_modify.setText("Modify");
        btn_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Ph. No.");

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        ((AbstractDocument)client_mob.getDocument()).setDocumentFilter(
            new com.employeemanagement.utility.NumericDocumentFilter());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Address");

        btn_del.setText("Delete");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(client_mob, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(client_phn)
                                .addComponent(client_name, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addComponent(btn_modify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(client_code_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(client_code_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(client_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(client_mob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(client_phn)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_cancel)
                    .addComponent(btn_del)
                    .addComponent(btn_modify))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        IPersistence ip = Persistence.getInstance();
        String clientID = ip.getClientID();


        if (!client_name.getText().equalsIgnoreCase("")) {
            Client clt = new Client();
            clt.setClient_name(client_name.getText());
            clt.setClient_mob1(client_mob.getText());
            clt.setClient_mob2(client_phn.getText());
            clt.setClient_add(client_add.getText());
            clt.setClient_id(clientID);
            ip.saveClient(clt);

            this.dispose();
            JFrame j = new JFrame();
            j.setAlwaysOnTop(true);
            j.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            j.setVisible(false);


            JOptionPane.showMessageDialog(j, "Client Added Succesfully", "Dialog",
                    JOptionPane.INFORMATION_MESSAGE);


        } else {



            JDialog dialog = new JOptionPane("Please put client name").createDialog(ClientFrame.this, "Alert");
            Point dialogLoc = dialog.getLocation();
            Point parentLoc = ClientFrame.this.getLocation();
            //dialog.setLocation(parentLoc.x + ClientFrame.this.getWidth(), dialogLoc.y);
            dialog.setVisible(true);
        }








    }//GEN-LAST:event_btn_saveActionPerformed

    private void client_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_codeActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyActionPerformed
        // TODO add your handling code here:
        try {

            IPersistence ip = Persistence.getInstance();
            Client client = new Client();

            client.setClient_id(client_code.getText());
            client.setClient_mob1(client_mob.getText());
            client.setClient_mob2(client_phn.getText());
            client.setClient_name(client_name.getText());
            client.setClient_add(client_add.getText());
            Boolean flag = ip.updateClient(client);

            if (flag) {
                System.out.print("Data persisted succesfully");
                JOptionPane.showMessageDialog(new JFrame(), "Client data Updated susscessfully", "Dialog", JOptionPane.INFORMATION_MESSAGE);
                listFrame.reloadTableData();
                mainFrame.reloadTableData();
                mainFrame.reloadTableDataCompletedAssignment();
                mainFrame.reloadTableDataCurrentAssignment();
            } else {
                System.out.print("Data not persisted");
                JOptionPane.showMessageDialog(new JFrame(), "Data not persisted", "Dialog", JOptionPane.ERROR_MESSAGE);
            }

            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_modifyActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        String clinetID = client_code.getText();

        IPersistence ip = Persistence.getInstance();

        //if(clinetID !=null && !clinetID.equalsIgnoreCase("")){
        //int dialogButton = JOptionPane.YES_NO_OPTION;
        //int value = JOptionPane.showConfirmDialog (null, "Do you want to delete client?","Warning",dialogButton);
        //}
        boolean flag = ip.deleteClient(clinetID);

        if (flag) {
            System.out.print("Data deleted succesfully");
            JOptionPane.showMessageDialog(new JFrame(), "Client deleted susscessfully", "Dialog", JOptionPane.INFORMATION_MESSAGE);
            listFrame.reloadTableData();
            mainFrame.reloadTableData();
            mainFrame.reloadTableDataCompletedAssignment();
            mainFrame.reloadTableDataCurrentAssignment();
        } else {
            System.out.print("Data not deleted");
            JOptionPane.showMessageDialog(new JFrame(), "Client not deleted", "Dialog", JOptionPane.ERROR_MESSAGE);
        }

        this.dispose();



    }//GEN-LAST:event_btn_delActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_modify;
    private javax.swing.JButton btn_save;
    private javax.swing.JTextArea client_add;
    private javax.swing.JTextField client_code;
    private javax.swing.JPanel client_code_panel;
    private javax.swing.JTextField client_mob;
    private javax.swing.JTextField client_name;
    private javax.swing.JTextField client_phn;
    private javax.swing.JLabel headerText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
