/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empmanagement.screens;

import com.employeemanagement.common.Common;
import com.employeemanagement.models.Employee;
import com.employeemanagement.utility.PrintImages;
import static com.empmanagement.screens.EmployeeDisplayPanel.resize;
import static com.empmanagement.screens.EmployeeManipulationFrame.imagePath;
import static com.empmanagement.screens.EmployeeManipulationFrame.resize;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author arup
 */
public class EmployeeDetailView extends javax.swing.JFrame {
    
    Employee emp =null;
    EmployeeManipulationFrame emf= null;
    int labelHeight = 650;
    int labelWidth = 550;
            

    /**
     * Creates new form EmployeeDetailView
     */
    public EmployeeDetailView(Employee emp,EmployeeManipulationFrame emf) {
        initComponents();
        this.emp=emp;
        this.emf=emf;
        initOtherComponent();
        setEmployeeDetail(emp);
        
    }
    
    public void initOtherComponent(){
    main.setVisible(true);
    chk_biodata.setSelected(true);
    voter_back_panel.setVisible(true);
    voter_front_panel.setVisible(true);
    pan_panel.setVisible(true);
    panchayet_panel.setVisible(true);
    
    }
    
    public void setEmployeeDetail(Employee emp){
    
        String empName  = emp.getF_name() +" "+emp.getM_name() +" "+emp.getL_name();
        empName = empName.trim().replaceAll("( +)", " ");
        name.setText(empName);
        
        gaurdian.setText(emp.getGuardian_name());
        age.setText(emp.getAge().toString());
        
        String mobleNo = "<html>"+emp.getMob1();
        if(!emp.getMob2().equalsIgnoreCase(""))
            mobleNo += "<BR/>"+emp.getMob2();
        mobleNo+="</html>";
        
        mobile.setText(mobleNo);
        address.setText("<html><div style='width:250px;display:inline; word-wrap: break-word;'>"+emp.getAddress()+"</div></html>");
        landmark.setText("<html><div style='width:250px;display:inline; word-wrap: break-word;'>"+emp.getLandmark()+"</div></html>");
        dt_admission.setText(Common.getDateFormatter().format(emp.getAdm_dt()));
        post.setText(emp.getPost());
        
         if(emp.getPhoto_ID() != null ){
            
            String imgPath = emp.getPhoto_ID();
            System.out.println(imgPath);
          
            if(!imgPath.equalsIgnoreCase("") && imgPath.length() > 0){
                
            File file = new File(imgPath);
            BufferedImage bufferedImage = null;
            try {
                bufferedImage = ImageIO.read(file);
                bufferedImage = Common.resize(bufferedImage, photo.getWidth(), photo.getHeight());
                //Image image = bufferedImage;
                ImageIcon imageIcon = new ImageIcon(bufferedImage);
                photo.setIcon(imageIcon);
                
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            }
            else
                photo.setText("No Photo");
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        chk_biodata = new javax.swing.JCheckBox();
        chk_voterfront = new javax.swing.JCheckBox();
        chk_voterback = new javax.swing.JCheckBox();
        chk_panchayet = new javax.swing.JCheckBox();
        chk_other = new javax.swing.JCheckBox();
        chk_pan = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        main = new javax.swing.JPanel();
        biodata_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gaurdian = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        emp_detail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        landmark = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dt_admission = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        post = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        voter_front_panel = new javax.swing.JPanel();
        lbl_voterfront = new javax.swing.JLabel();
        pan_panel = new javax.swing.JPanel();
        panchayet_panel = new javax.swing.JPanel();
        voter_back_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(254, 254, 254));
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Select document ");

        chk_biodata.setForeground(new java.awt.Color(254, 254, 254));
        chk_biodata.setText("Biodata");
        chk_biodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_biodataActionPerformed(evt);
            }
        });

        chk_voterfront.setForeground(new java.awt.Color(254, 254, 254));
        chk_voterfront.setText("Voter ID(Front)");
        chk_voterfront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_voterfrontActionPerformed(evt);
            }
        });

        chk_voterback.setForeground(new java.awt.Color(254, 254, 254));
        chk_voterback.setText("Voter ID(Back)");
        chk_voterback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_voterbackActionPerformed(evt);
            }
        });

        chk_panchayet.setForeground(new java.awt.Color(254, 254, 254));
        chk_panchayet.setText("Panchayet");

        chk_other.setForeground(new java.awt.Color(254, 254, 254));
        chk_other.setText("Other");

        chk_pan.setForeground(new java.awt.Color(254, 254, 254));
        chk_pan.setText("Pan");
        chk_pan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_panActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chk_biodata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_voterfront)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_voterback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_pan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chk_panchayet))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ok)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chk_other, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_biodata)
                    .addComponent(chk_voterfront)
                    .addComponent(chk_voterback)
                    .addComponent(chk_panchayet)
                    .addComponent(chk_other)
                    .addComponent(chk_pan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        biodata_panel.setBackground(new java.awt.Color(254, 254, 254));
        biodata_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setText("Name");

        name.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        name.setText("Arup");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Gaurdian's Name");

        gaurdian.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        gaurdian.setText("Arup");

        emp_detail.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        emp_detail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emp_detail.setText("Employee Detail");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("Address");

        Age.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        Age.setText("Age");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Mob no.");

        age.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        age.setText("30");

        mobile.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        mobile.setText("9903012949 , 9804546217");
        mobile.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        address.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        address.setText("Tollygunge");
        address.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        landmark.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        landmark.setText("Kolkata-700040");
        landmark.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel7.setText("Date of admission");

        dt_admission.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        dt_admission.setText("13th may,2013");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel9.setText("Post");

        post.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        post.setText("12 Hrs Ayaah");

        photo.setBackground(new java.awt.Color(1, 1, 1));
        photo.setText("pho");
        photo.setMaximumSize(new java.awt.Dimension(24, 17));
        photo.setMinimumSize(new java.awt.Dimension(24, 17));
        photo.setPreferredSize(new java.awt.Dimension(24, 17));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("How to go");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel6.setText("N.B : This is computarised datails of this employee which is given for date of admission");

        javax.swing.GroupLayout biodata_panelLayout = new javax.swing.GroupLayout(biodata_panel);
        biodata_panel.setLayout(biodata_panelLayout);
        biodata_panelLayout.setHorizontalGroup(
            biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodata_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(biodata_panelLayout.createSequentialGroup()
                                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gaurdian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobile))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(320, 320, 320))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addGroup(biodata_panelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dt_admission, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(landmark, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        biodata_panelLayout.setVerticalGroup(
            biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodata_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(emp_detail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name))
                        .addGap(18, 18, 18)
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gaurdian, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landmark, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_admission, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(110, 110, 110))
        );

        voter_front_panel.setBackground(new java.awt.Color(254, 254, 254));
        voter_front_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_voterfront.setBackground(new java.awt.Color(254, 254, 254));
        lbl_voterfront.setForeground(new java.awt.Color(254, 254, 254));
        lbl_voterfront.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout voter_front_panelLayout = new javax.swing.GroupLayout(voter_front_panel);
        voter_front_panel.setLayout(voter_front_panelLayout);
        voter_front_panelLayout.setHorizontalGroup(
            voter_front_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, voter_front_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_voterfront, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        voter_front_panelLayout.setVerticalGroup(
            voter_front_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voter_front_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_voterfront, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pan_panelLayout = new javax.swing.GroupLayout(pan_panel);
        pan_panel.setLayout(pan_panelLayout);
        pan_panelLayout.setHorizontalGroup(
            pan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pan_panelLayout.setVerticalGroup(
            pan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panchayet_panelLayout = new javax.swing.GroupLayout(panchayet_panel);
        panchayet_panel.setLayout(panchayet_panelLayout);
        panchayet_panelLayout.setHorizontalGroup(
            panchayet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panchayet_panelLayout.setVerticalGroup(
            panchayet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout voter_back_panelLayout = new javax.swing.GroupLayout(voter_back_panel);
        voter_back_panel.setLayout(voter_back_panelLayout);
        voter_back_panelLayout.setHorizontalGroup(
            voter_back_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        voter_back_panelLayout.setVerticalGroup(
            voter_back_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(voter_front_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 597, Short.MAX_VALUE)
                    .addComponent(biodata_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voter_back_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panchayet_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(biodata_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voter_front_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voter_back_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pan_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(panchayet_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(main);

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2249, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        
        
        
        System.out.print(" Biodata : "+ chk_biodata.isSelected());
        System.out.print(" Voter Front : "+ chk_voterfront.isSelected());
        System.out.print(" Voter Back : "+ chk_voterback.isSelected());
        System.out.print(" Panchayet : "+ chk_panchayet.isSelected());
        System.out.print(" Others : "+ chk_other.isSelected());
        
        
        if(chk_biodata.isSelected()){
          Toolkit tkp = biodata_panel.getToolkit();
          PrintJob pjp = tkp.getPrintJob(this, null, null);
          Graphics g = pjp.getGraphics();
         
          biodata_panel.print(g);
          g.dispose();
          pjp.end();
        }
          
          printDocument(emp);
         
    }//GEN-LAST:event_okActionPerformed

    private void chk_voterfrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_voterfrontActionPerformed
        // TODO add your handling code here:
        
        File f = new File(this.emp.getVoter_ID());
//        if(chk_voterfront.isSelected()&& f.exists()){
//            voter_front_panel.setVisible(true);
//            BufferedImage bufferedImage = null;
//             try {
//                bufferedImage = ImageIO.read(f);
//               // bufferedImage = resize(bufferedImage, 500, 700);
//                //Image image = bufferedImage;
//                ImageIcon imageIcon = new ImageIcon(bufferedImage);
//                lbl_voterfront.setIcon(imageIcon);
//                
//                 
//                
//                
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
//        
//        else{
//        voter_front_panel.setVisible(false);
//        
//        }
        
        
        /*-------------------------------------------*/
        
         if(chk_voterfront.isSelected()&& f.exists()){
                voter_front_panel.setVisible(true);
                voter_front_panel.setPreferredSize(new Dimension(labelWidth, labelHeight));
                lbl_voterfront.setVisible(true);
                lbl_voterfront.setPreferredSize(new Dimension(labelWidth-20, labelHeight - 20));
              
                BufferedImage bufferedImage = null;
                ImageIcon imageIcon = null;
                Image imgg = null;
                try {
                    bufferedImage = ImageIO.read(f);
                    int h = bufferedImage.getHeight();
                    int w = bufferedImage.getWidth();
                
            
            if(h < labelHeight && w < labelWidth){
                
            bufferedImage = Common.resize(bufferedImage, bufferedImage.getWidth(), bufferedImage.getHeight());
            imageIcon = new ImageIcon(bufferedImage);      
                  
            }
            
            else{
           
            imgg =  bufferedImage.getScaledInstance(labelHeight, labelWidth, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(imgg);
            }
                       
            lbl_voterfront.setText("");
            lbl_voterfront.setIcon(imageIcon);
            } catch (Exception e) {
                    e.printStackTrace();
                }
         }
         
          else{
               
             voter_front_panel.setVisible(false);   
                
                }
        
        
        
        /*------------------------------------------- */
    }//GEN-LAST:event_chk_voterfrontActionPerformed

    private void chk_voterbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_voterbackActionPerformed
        // TODO add your handling code here:
        
        if(chk_voterback.isSelected())
        {
            voter_back_panel.setPreferredSize(new Dimension(labelWidth, labelHeight));
            voter_back_panel.setVisible(true);
        
        
        }
        
        else
            voter_back_panel.setVisible(false);
        
//        
//        File f = new File(this.emp.getVoterBack_ID());
//        
//        if(chk_voterback.isSelected() && f.exists()){
//        voter_back_panel.setVisible(true);
//        }
//        
//        else{
//        voter_back_panel.setVisible(false);
//        
//        }
    }//GEN-LAST:event_chk_voterbackActionPerformed

    private void chk_biodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_biodataActionPerformed
        // TODO add your handling code here:
        if(chk_biodata.isSelected()){
        
        biodata_panel.setVisible(true);
        
        }
        
        else{
        
        biodata_panel.setVisible(false);
        }
    }//GEN-LAST:event_chk_biodataActionPerformed

    private void chk_panActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_panActionPerformed
        // TODO add your handling code here:
        if(chk_pan.isSelected())
            pan_panel.setVisible(true);
        
        else
            pan_panel.setVisible(false);
    }//GEN-LAST:event_chk_panActionPerformed

    
    public void printDocument(Employee emp){
        
    ArrayList images = new ArrayList();   
    String path = "";    
    FileInputStream fis=null;
    BufferedImage ri = null;
    File f = null;
        try {
            path = emp.getVoter_ID();
            f = new File(path);
            if(f.exists() && chk_voterfront.isSelected()){
                fis = new FileInputStream((path.toString()));
                ri = ImageIO.read(fis);
                images.add(ri);
            }  
            
            path = emp.getVoterBack_ID();
            f = new File(path);
            if(f.exists() && chk_voterback.isSelected()){            
            fis = new FileInputStream((path.toString()));  
            ri = ImageIO.read(fis);  
            images.add(ri);  
            }
            
            path = emp.getPan_ID();
            f = new File(path);
            if(f.exists() && chk_pan.isSelected()){            
                fis = new FileInputStream((path.toString()));  
                ri = ImageIO.read(fis);  
                images.add(ri);  
            }
            
            path = emp.getPanchayat();
            f = new File(path);
            if(f.exists()&&chk_panchayet.isSelected()){                        
                fis = new FileInputStream((path.toString()));  
                ri = ImageIO.read(fis);  
                images.add(ri);  
            }
            
            path = emp.getOtherDoc();
            f = new File(path);
            if(f.exists()&& chk_other.isSelected()){                                    
            fis = new FileInputStream((path.toString()));  
            ri = ImageIO.read(fis);  
            images.add(ri);  
            }

            fis.close();  
            ri.flush();                   
            ri = null;    
            
            new PrintImages().print(images, "", "");     
                    
    
    } catch (Exception ex) {
            Logger.getLogger(EmployeeDetailView.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetailView(null,null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JPanel biodata_panel;
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox chk_biodata;
    private javax.swing.JCheckBox chk_other;
    private javax.swing.JCheckBox chk_pan;
    private javax.swing.JCheckBox chk_panchayet;
    private javax.swing.JCheckBox chk_voterback;
    private javax.swing.JCheckBox chk_voterfront;
    private javax.swing.JLabel dt_admission;
    private javax.swing.JLabel emp_detail;
    private javax.swing.JLabel gaurdian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel landmark;
    private javax.swing.JLabel lbl_voterfront;
    private javax.swing.JPanel main;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JButton ok;
    private javax.swing.JPanel pan_panel;
    private javax.swing.JPanel panchayet_panel;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel post;
    private javax.swing.JPanel voter_back_panel;
    private javax.swing.JPanel voter_front_panel;
    // End of variables declaration//GEN-END:variables
}
