/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empmanagement.screens;

import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

import com.employeemanagement.common.Common;
import com.employeemanagement.models.Employee;
import com.empmanagement.persistence.IPersistence;
import com.empmanagement.persistence.Persistence;

/**
 *
 * @author user
 */
public class EmployeeDisplayPanel extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDisplayPanel
     */

    MainFrame mainFrame;
    Employee employee;
    EmployeeListFrame listframe;

    String logoPath = "com/empmanagement/screens/ss-center.jpg";

    public EmployeeDisplayPanel(MainFrame mainFrame,
	    EmployeeListFrame listframe, Employee employee) {
	this.mainFrame = mainFrame;
	this.listframe = listframe;
	this.employee = employee;
	initComponents();

	if (employee.getPhoto_ID() != null) {

	    String imgPath = employee.getPhoto_ID();
	    System.out.println(imgPath);

	    if (!imgPath.equalsIgnoreCase("") && imgPath.length() > 0) {

		File file = new File(imgPath);
		BufferedImage bufferedImage = null;
		try {
		    bufferedImage = ImageIO.read(file);
		    bufferedImage = resize(bufferedImage, photo.getWidth(),
			    photo.getHeight());
		    // Image image = bufferedImage;
		    ImageIcon imageIcon = new ImageIcon(bufferedImage);
		    photo.setIcon(imageIcon);

		} catch (Exception e) {
		    e.printStackTrace();
		}

	    } else
		photo.setText("No Photo");

	}

	if (employee.getF_name() != null) {
	    name.setText(employee.getF_name() + " " + employee.getM_name()
		    + " " + employee.getL_name());
	    // headerName.setText(employee.getF_name() + " " +
	    // employee.getM_name() + " " + employee.getL_name());
	    headerName.setText("");
	}

	if (employee.getEmp_id() != null) {
	    code.setText(employee.getEmp_id());
	} else
	    code.setText("");

	if (employee.getPost() != null) {
	    post.setText(employee.getPost());
	} else
	    post.setText("");

	if (employee.getGuardian_name() != null) {
	    guardian.setText(employee.getGuardian_name());
	} else
	    guardian.setText("");
	//
	// if((employee.getMob1() != null)){
	// phone.setText(employee.getMob1());
	// }
	// else
	// phone.setText("");

	String mobleNo = "<html>" + employee.getMob1();

	mobleNo += "</html>";

	phone.setText(mobleNo);

	if (employee.getAge() != 0) {
	    age.setText(employee.getAge().toString());
	} else
	    age.setText("");

	if ((employee.getAddress() != null)) {
	    // address.setText(employee.getAddress());

	    address.setText("<html><div style=' width:150px;display:inline; word-wrap: break-word;'>"
		    + employee.getAddress()
		    + "<BR>"
		    + employee.getLandmark()
		    + "</div></html>");
	}

	else
	    address.setText("");

	if (employee.getLandmark() != null
		|| !employee.getLandmark().equalsIgnoreCase("")) {
	    // lbl_landmark.setText(employee.getLandmark());

	}
	// else

	// lbl_landmark.setText("");

	SimpleDateFormat formater = new SimpleDateFormat("dd MMM, yyyy");
	Date dt = new Date();

	dt_print.setText(formater.format(dt));

    }

    public static BufferedImage resize(BufferedImage image, int width,
	    int height) {
	BufferedImage bi = new BufferedImage(width, height,
		BufferedImage.TRANSLUCENT);
	Graphics2D g2d = (Graphics2D) bi.createGraphics();
	g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING,
		RenderingHints.VALUE_RENDER_QUALITY));
	g2d.drawImage(image, 0, 0, width, height, null);
	g2d.dispose();
	return bi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jPanel5 = new javax.swing.JPanel();
	jPanel3 = new javax.swing.JPanel();
	jButtonEditEmp = new javax.swing.JButton();
	jButtonPrintEmp = new javax.swing.JButton();
	delete = new javax.swing.JToggleButton();
	icard_panel = new javax.swing.JPanel();
	jPanel4 = new javax.swing.JPanel();
	code = new javax.swing.JLabel();
	jLabel7 = new javax.swing.JLabel();
	address = new javax.swing.JLabel();
	name = new javax.swing.JLabel();
	guardian = new javax.swing.JLabel();
	phone = new javax.swing.JLabel();
	jLabel5 = new javax.swing.JLabel();
	age = new javax.swing.JLabel();
	jPanel2 = new javax.swing.JPanel();
	photo = new javax.swing.JLabel();
	post = new javax.swing.JLabel();
	jLabel2 = new javax.swing.JLabel();
	jLabel3 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jLabel6 = new javax.swing.JLabel();
	jLabel8 = new javax.swing.JLabel();
	jPanel6 = new javax.swing.JPanel();
	comName = new javax.swing.JLabel();
	jLabel10 = new javax.swing.JLabel();
	jLabel11 = new javax.swing.JLabel();
	jLabel12 = new javax.swing.JLabel();
	print_dt = new javax.swing.JLabel();
	dt_print = new javax.swing.JLabel();
	jLabel9 = new javax.swing.JLabel();
	jSeparator2 = new javax.swing.JSeparator();
	txt_mesg = new javax.swing.JButton();
	jPanel1 = new javax.swing.JPanel();
	jLabel1 = new javax.swing.JLabel();
	headerName = new javax.swing.JLabel();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	jPanel5.setBackground(new java.awt.Color(255, 255, 255));

	jPanel3.setBackground(new java.awt.Color(255, 255, 255));

	jButtonEditEmp.setText("Edit");
	jButtonEditEmp.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jButtonEditEmpActionPerformed(evt);
	    }
	});

	jButtonPrintEmp.setText("Print");
	jButtonPrintEmp.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jButtonPrintEmpActionPerformed(evt);
	    }
	});

	delete.setText("Delete");
	delete.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		deleteActionPerformed(evt);
	    }
	});

	icard_panel.setBackground(new java.awt.Color(254, 254, 254));
	icard_panel.setBorder(javax.swing.BorderFactory
		.createLineBorder(new java.awt.Color(0, 0, 0)));
	icard_panel.setForeground(new java.awt.Color(255, 255, 255));

	jPanel4.setBackground(new java.awt.Color(255, 255, 255));
	jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
		0, 0, 0), 2, true));

	code.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
	code.setText("Code");

	jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
	jLabel7.setText("Age");

	address.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
	address.setText("Address");
	address.setVerticalAlignment(javax.swing.SwingConstants.TOP);

	name.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
	name.setText("Name");

	guardian.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
	guardian.setText("Guardian");

	phone.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
	phone.setText("Phone No.");

	jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
	jLabel5.setText("Emp Code");

	age.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
	age.setText("age");

	jPanel2.setBackground(new java.awt.Color(254, 254, 254));
	jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(
		new java.awt.Color(0, 0, 0), 2));

	photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

	javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
		jPanel2);
	jPanel2.setLayout(jPanel2Layout);
	jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addComponent(photo,
		javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE));
	jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addComponent(photo,
		javax.swing.GroupLayout.DEFAULT_SIZE,
		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

	post.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
	post.setText("post");

	jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
	jLabel2.setText("Name");

	jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
	jLabel3.setText("Post");

	jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
	jLabel4.setText("Guardian's Name");

	jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
	jLabel6.setText("Phone No.");

	jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
	jLabel8.setText("Address");

	jPanel6.setBackground(new java.awt.Color(254, 254, 254));
	jPanel6.setBorder(javax.swing.BorderFactory
		.createLineBorder(new java.awt.Color(0, 0, 0)));

	comName.setBackground(new java.awt.Color(254, 254, 254));
	comName.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
	comName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	comName.setIcon(new javax.swing.ImageIcon(getClass().getResource(
		"/com/empmanagement/screens/big_logo.png"))); // NOI18N

	jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
	jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	jLabel10.setText("Tollygunge,Kolkata,WB,India");

	jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
	jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	jLabel11.setText("Ph-1234567890 / 0987654321");

	jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 7)); // NOI18N
	jLabel12.setText("NURSE AND AYAH AVAILABLE");

	javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
		jPanel6);
	jPanel6.setLayout(jPanel6Layout);
	jPanel6Layout.setHorizontalGroup(jPanel6Layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
			javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		.addComponent(comName,
			javax.swing.GroupLayout.Alignment.TRAILING,
			javax.swing.GroupLayout.DEFAULT_SIZE,
			javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		.addComponent(jLabel10,
			javax.swing.GroupLayout.Alignment.TRAILING,
			javax.swing.GroupLayout.DEFAULT_SIZE,
			javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		.addGroup(
			javax.swing.GroupLayout.Alignment.TRAILING,
			jPanel6Layout
				.createSequentialGroup()
				.addContainerGap(
					javax.swing.GroupLayout.DEFAULT_SIZE,
					Short.MAX_VALUE).addComponent(jLabel12)
				.addGap(42, 42, 42)));
	jPanel6Layout
		.setVerticalGroup(jPanel6Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel6Layout
					.createSequentialGroup()
					.addComponent(
						comName,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						55,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(1, 1, 1)
					.addComponent(jLabel12)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(
						jLabel10,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						15,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(
						jLabel11,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
					.addGap(6, 6, 6)));

	print_dt.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
	print_dt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
	print_dt.setText("Print Date");

	dt_print.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
	dt_print.setText("2nd June,2013");

	jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
	jLabel9.setForeground(new java.awt.Color(241, 26, 26));
	jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	jLabel9.setText("THIS CARD VALID ONLY ONE MONTH");

	javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
		jPanel4);
	jPanel4.setLayout(jPanel4Layout);
	jPanel4Layout
		.setHorizontalGroup(jPanel4Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel4Layout
					.createSequentialGroup()
					.addContainerGap()
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(
								jPanel4Layout
									.createSequentialGroup()
									.addGroup(
										jPanel4Layout
											.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
											.addComponent(
												jLabel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												69,
												javax.swing.GroupLayout.PREFERRED_SIZE)
											.addGroup(
												jPanel4Layout
													.createSequentialGroup()
													.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														100,
														javax.swing.GroupLayout.PREFERRED_SIZE)
													.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
													.addComponent(
														name,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														166,
														javax.swing.GroupLayout.PREFERRED_SIZE))
											.addComponent(
												jLabel9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												304,
												javax.swing.GroupLayout.PREFERRED_SIZE))
									.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
							.addGroup(
								jPanel4Layout
									.createSequentialGroup()
									.addGroup(
										jPanel4Layout
											.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
											.addGroup(
												jPanel4Layout
													.createSequentialGroup()
													.addComponent(
														jLabel5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														61,
														javax.swing.GroupLayout.PREFERRED_SIZE)
													.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
													.addComponent(
														code,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														75,
														javax.swing.GroupLayout.PREFERRED_SIZE)
													.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
													.addComponent(
														print_dt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														63,
														javax.swing.GroupLayout.PREFERRED_SIZE)
													.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
													.addComponent(
														dt_print,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														83,
														javax.swing.GroupLayout.PREFERRED_SIZE)
													.addGap(1,
														1,
														1))
											.addComponent(
												jSeparator2,
												javax.swing.GroupLayout.Alignment.LEADING)
											.addGroup(
												jPanel4Layout
													.createParallelGroup(
														javax.swing.GroupLayout.Alignment.TRAILING)
													.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														jPanel4Layout
															.createSequentialGroup()
															.addComponent(
																jPanel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
															.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
															.addComponent(
																jPanel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
													.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														jPanel4Layout
															.createSequentialGroup()
															.addGroup(
																jPanel4Layout
																	.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																	.addGroup(
																		jPanel4Layout
																			.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																			.addComponent(
																				jLabel7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																			.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																			.addComponent(
																				jLabel4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				100,
																				Short.MAX_VALUE))
																	.addComponent(
																		jLabel8,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		100,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
															.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
															.addGroup(
																jPanel4Layout
																	.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																	.addComponent(
																		post,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		157,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addComponent(
																		age,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		54,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addComponent(
																		guardian,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		165,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addComponent(
																		address,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																	.addComponent(
																		phone,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		183,
																		Short.MAX_VALUE)))))
									.addGap(0,
										0,
										Short.MAX_VALUE)))));
	jPanel4Layout
		.setVerticalGroup(jPanel4Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel4Layout
					.createSequentialGroup()
					.addContainerGap()
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(
								jPanel4Layout
									.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
									.addComponent(
										code,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										19,
										javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(
										print_dt)
									.addComponent(
										dt_print))
							.addComponent(
								jLabel5,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								21,
								javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING,
								false)
							.addComponent(
								jPanel6,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
							.addComponent(
								jPanel2,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(jLabel2)
							.addComponent(name))
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(
								jLabel4,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								15,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(
								guardian,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								15,
								javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING,
								false)
							.addComponent(
								jLabel7,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
							.addComponent(
								age,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(jLabel3)
							.addComponent(post))
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING,
								false)
							.addComponent(
								jLabel6,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
							.addComponent(
								phone,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(
						jPanel4Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
							.addComponent(jLabel8)
							.addComponent(
								address,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								60,
								javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
					.addComponent(
						jSeparator2,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jLabel9)
					.addGap(58, 58, 58)));

	javax.swing.GroupLayout icard_panelLayout = new javax.swing.GroupLayout(
		icard_panel);
	icard_panel.setLayout(icard_panelLayout);
	icard_panelLayout.setHorizontalGroup(icard_panelLayout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			icard_panelLayout
				.createSequentialGroup()
				.addGap(19, 19, 19)
				.addComponent(jPanel4,
					javax.swing.GroupLayout.PREFERRED_SIZE,
					0, Short.MAX_VALUE).addContainerGap()));
	icard_panelLayout
		.setVerticalGroup(icard_panelLayout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				icard_panelLayout
					.createSequentialGroup()
					.addContainerGap()
					.addComponent(
						jPanel4,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						363, Short.MAX_VALUE)
					.addContainerGap()));

	txt_mesg.setIcon(new javax.swing.ImageIcon(getClass().getResource(
		"/com/empmanagement/screens/File_icon.png"))); // NOI18N
	txt_mesg.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		txt_mesgActionPerformed(evt);
	    }
	});

	javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
		jPanel3);
	jPanel3.setLayout(jPanel3Layout);
	jPanel3Layout
		.setHorizontalGroup(jPanel3Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel3Layout
					.createSequentialGroup()
					.addGap(124, 124, 124)
					.addComponent(txt_mesg)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jButtonEditEmp)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(delete)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jButtonPrintEmp)
					.addContainerGap(
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE))
			.addGroup(
				jPanel3Layout
					.createSequentialGroup()
					.addContainerGap()
					.addComponent(
						icard_panel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)));
	jPanel3Layout
		.setVerticalGroup(jPanel3Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel3Layout
					.createSequentialGroup()
					.addGroup(
						jPanel3Layout
							.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(
								jButtonEditEmp)
							.addComponent(
								jButtonPrintEmp)
							.addComponent(delete)
							.addComponent(txt_mesg))
					.addGap(18, 18, 18)
					.addComponent(
						icard_panel,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(0, 0, Short.MAX_VALUE)));

	jPanel1.setBackground(new java.awt.Color(0, 0, 0));

	jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
	jLabel1.setForeground(new java.awt.Color(255, 255, 255));
	jLabel1.setText("  Employee Details");

	headerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
	headerName.setForeground(new java.awt.Color(255, 255, 255));

	javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
		jPanel1);
	jPanel1.setLayout(jPanel1Layout);
	jPanel1Layout
		.setHorizontalGroup(jPanel1Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel1Layout
					.createSequentialGroup()
					.addContainerGap()
					.addComponent(
						jLabel1,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						152,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(
						headerName,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						189,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(0, 2, Short.MAX_VALUE)));
	jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addGroup(
		jPanel1Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.BASELINE)
			.addComponent(jLabel1,
				javax.swing.GroupLayout.PREFERRED_SIZE, 32,
				javax.swing.GroupLayout.PREFERRED_SIZE)
			.addComponent(headerName,
				javax.swing.GroupLayout.PREFERRED_SIZE, 32,
				javax.swing.GroupLayout.PREFERRED_SIZE)));

	javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
		jPanel5);
	jPanel5.setLayout(jPanel5Layout);
	jPanel5Layout.setHorizontalGroup(jPanel5Layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			jPanel5Layout
				.createSequentialGroup()
				.addContainerGap()
				.addComponent(jPanel3,
					javax.swing.GroupLayout.DEFAULT_SIZE,
					javax.swing.GroupLayout.DEFAULT_SIZE,
					Short.MAX_VALUE).addContainerGap())
		.addGroup(
			jPanel5Layout
				.createSequentialGroup()
				.addGap(20, 20, 20)
				.addComponent(jPanel1,
					javax.swing.GroupLayout.PREFERRED_SIZE,
					javax.swing.GroupLayout.DEFAULT_SIZE,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(
					javax.swing.GroupLayout.DEFAULT_SIZE,
					Short.MAX_VALUE)));
	jPanel5Layout
		.setVerticalGroup(jPanel5Layout
			.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel5Layout
					.createSequentialGroup()
					.addContainerGap()
					.addComponent(
						jPanel1,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(
						jPanel3,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap(13, Short.MAX_VALUE)));

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
		getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addGroup(
		javax.swing.GroupLayout.Alignment.TRAILING,
		layout.createSequentialGroup()
			.addContainerGap()
			.addComponent(jPanel5,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				Short.MAX_VALUE).addContainerGap()));
	layout.setVerticalGroup(layout.createParallelGroup(
		javax.swing.GroupLayout.Alignment.LEADING).addGroup(
		layout.createSequentialGroup()
			.addContainerGap()
			.addComponent(jPanel5,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				Short.MAX_VALUE).addContainerGap()));

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditEmpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEditEmpActionPerformed

	EmployeeManipulationFrame internalFrame = new EmployeeManipulationFrame(
		"Employee Manipulation Panel", mainFrame, listframe, employee);
	internalFrame.setBounds(170, 30, 150, 70);
	internalFrame.setPreferredSize(new java.awt.Dimension(1000, 750));
	internalFrame.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
	internalFrame.setVisible(true);
	internalFrame.pack();
	this.dispose();
    }// GEN-LAST:event_jButtonEditEmpActionPerformed

    private void jButtonPrintEmpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPrintEmpActionPerformed
	Toolkit tkp = icard_panel.getToolkit();
	PrintJob pjp = tkp.getPrintJob(this, null, null);
	Graphics g = pjp.getGraphics();
	icard_panel.print(g);
	g.dispose();
	pjp.end();
    }// GEN-LAST:event_jButtonPrintEmpActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteActionPerformed

	int more = JOptionPane.showConfirmDialog(null,
		"Do you really want to delete ?", "Confirm delete",
		JOptionPane.YES_NO_OPTION);

	if (more == 0) {
	    String empCode = code.getText();
	    IPersistence ip = Persistence.getInstance();
	    boolean flag = ip.deleteEmployee(empCode);

	    if (flag) {
		String mesg = "Permanently deleted " + employee.getF_name()
			+ " " + employee.getM_name() + " "
			+ employee.getL_name();
		JOptionPane.showMessageDialog(new JFrame(), mesg, "Dialog",
			JOptionPane.INFORMATION_MESSAGE);

		if (listframe != null)
		    listframe.reloadTableData();
		mainFrame.reloadTableData();
		mainFrame.reloadTableDataCurrentAssignment();
		mainFrame.reloadTableDataCompletedAssignment();
		this.dispose();
	    } else {
		System.out.print("Data not persisted");
		JOptionPane.showMessageDialog(new JFrame(), "Error occured. ",
			"Dialog", JOptionPane.ERROR_MESSAGE);
	    }
	} else {

	}

    }// GEN-LAST:event_deleteActionPerformed

    private void txt_mesgActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_mesgActionPerformed
	// TODO add your handling code here:
	try {
	    // TODO add your handling code here:

	    String mesgPath = Common.getMessageDir()
		    + this.employee.getEmp_id() + ".txt";
	    File file = new File(mesgPath);

	    if (!file.exists())
		file.createNewFile();
	    Desktop.getDesktop().open(file);
	} catch (IOException ex) {
	    Logger.getLogger(EmployeeDisplayPanel.class.getName()).log(
		    Level.SEVERE, null, ex);
	}

    }// GEN-LAST:event_txt_mesgActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JLabel code;
    private javax.swing.JLabel comName;
    private javax.swing.JToggleButton delete;
    private javax.swing.JLabel dt_print;
    private javax.swing.JLabel guardian;
    private javax.swing.JLabel headerName;
    private javax.swing.JPanel icard_panel;
    private javax.swing.JButton jButtonEditEmp;
    private javax.swing.JButton jButtonPrintEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel post;
    private javax.swing.JLabel print_dt;
    private javax.swing.JButton txt_mesg;
    // End of variables declaration//GEN-END:variables
}
