/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empmanagement.screens;

import com.employeemanagement.models.Employee;
import com.empmanagement.providers.EmployeeCategories;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewAllEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    MainFrame mainFrame;
    
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    String dbUrl = "jdbc:mysql://localhost:3306/emp_management";
    String dbUsr = "arup";
    String dbPass = "arup";
    
    public ViewAllEmployee(String name,MainFrame mainFrame) 
    {    
        super("Employee Panel");
        
        initComponents();
        //setDefaultCloseOperation(JInternalFrame.EXIT_ON_CLOSE);
        this.setSize(600,600);
        initComponents();
        this.mainFrame = mainFrame;
        this.setResizable(true);
        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        initOtherComponents();
        pack();
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Employee> emplist= new ArrayList<Employee>();
  
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection (dbUrl,dbUsr,dbPass);
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM emp");
            while(rs.next())
            {
                 Employee emp3=new Employee();
                 emp3.setEmp_id(rs.getString("emp_id"));
                 emp3.setF_name(rs.getString("f_name"));
                 emp3.setM_name(rs.getString("m_name"));
                 emp3.setL_name(rs.getString("l_name"));
                 emp3.setAddress(rs.getString("address"));
                 emp3.setWayToGo(rs.getString("way"));
                 emp3.setGuardian_name(rs.getString("gurdian_name"));
                 emp3.setAge(rs.getInt("age"));
                 emp3.setPost(rs.getString("post"));
                 emp3.setPan_ID(rs.getString("photo_id"));
                 emp3.setVoter_ID(rs.getString("voter_id"));
                 
                 emplist.add(emp3);
               
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        finally
        {
            try {
                rs.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(ViewAllEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
 
        for(Employee emp:emplist)
        {
            tm.addRow(new Object[] {emp.getEmp_id(),emp.getF_name(),emp.getM_name(),emp.getL_name(),emp.getAddress(),emp.getWayToGo(),emp.getGuardian_name(),emp.getAge(),emp.getPost(),emp.getPan_ID(),emp.getVoter_ID()});
        }
}
    
    
    
    
    public void initOtherComponents(){
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        canvas1 = new java.awt.Canvas();

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("                                                          View All Employee Details");
        jLabel1.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "First Name", "Middle Name", "Last Name", "Address", "WayToGo", "Guardian Name", "Age", "Post", "Photo Id", "Voter Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 215, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2)
        {
            System.out.println("Double Click...");
            //DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            //int col = dtm.findColumn("Emp ID");  
            //int row = dtm.getRowCount();  
             JTable target = (JTable)evt.getSource();  
                    
             int selectedRow = target.getSelectedRow();  
             int selectedColumn = target.getSelectedColumn();  
                                          
             System.out.println("Selected row "+ " "+ selectedRow);  
             System.out.println("Selected column"+ " "+ selectedColumn);  
                  
            // Object selectedCellValue=target.getValueAt(selectedRow, selectedColumn);  
             //System.out.println("selectedCellValue "+" "+selectedCellValue);  
             
            Object selectedCellValue=target.getValueAt(selectedRow, 0);  
            String empId=String.valueOf(selectedCellValue);
            System.out.println("Selected column empId  "+ " "+ empId);
            try
            {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection (dbUrl,dbUsr,dbPass);
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM emp where emp_id='"+empId+"'");
            while(rs.next())
            {
                 Employee emp=new Employee();
                 emp.setEmp_id(rs.getString("emp_id"));
                 emp.setF_name(rs.getString("f_name"));
                 emp.setM_name(rs.getString("m_name"));
                 emp.setL_name(rs.getString("l_name"));
                 emp.setAddress(rs.getString("address"));
                 emp.setWayToGo(rs.getString("way"));
                 emp.setGuardian_name(rs.getString("gurdian_name"));
                 emp.setAge(rs.getInt("age"));
                 emp.setPost(rs.getString("post"));
                 emp.setPan_ID(rs.getString("photo_id"));
                 emp.setVoter_ID(rs.getString("voter_id"));   
                 System.out.println(">>>>>>>> "+ rs.getString("f_name"));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        finally
        {
            try {
                rs.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(ViewAllEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
             
        }
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
