/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empmanagement.test;

import com.employeemanagement.common.Common;
import com.employeemanagement.models.Employee;
import com.empmanagement.persistence.IPersistence;
import com.empmanagement.persistence.Persistence;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author arup
 */
public class MyPanel extends javax.swing.JPanel {

    
     Employee emp =null;
    /**
     * Creates new form MyPanel
     */
    public MyPanel(Employee employee) {
        initComponents();
        this.emp=emp;
        System.out.print("sss");
        setEmployeeDetail(employee);
    }
    
    
    public void setEmployeeDetail(Employee emp){
        
    
        String empName  = emp.getF_name() +" "+emp.getM_name() +" "+emp.getL_name();
        empName = empName.trim().replaceAll("( +)", " ");
        name.setText(empName);
        
        gaurdian.setText(emp.getGuardian_name());
        Integer empAge = emp.getAge();        
        if(empAge == null || empAge == 0)
        age.setText("");
        else
        age.setText(emp.getAge().toString());    
        
        String mobleNo = "<html>"+emp.getMob1();
        mobleNo+="</html>";        
        mobile.setText(mobleNo);
        
        String mobleNo2 = "<html><div style='width:320px;display:inline; word-wrap: break-word;'>"+emp.getMob2()+"</div></html>";
        mob2.setText(mobleNo2);
        
        address.setText("<html><div style='width:320px;display:inline; word-wrap: break-word;'>"+emp.getAddress()+"</div></html>");
        landmark.setText("<html><div style='width:320px;display:inline; word-wrap: break-word;'>"+emp.getWayToGo()+"</div></html>");
        location.setText("<html><div style='width:320px;display:inline;word-wrap:break-word;'>" + emp.getLandmark()+"</div></html>");
        dt_admission.setText(Common.getDateFormatter().format(emp.getAdm_dt()));
        post.setText(emp.getPost());
        
         if(emp.getPhoto_ID() != null ){
            
            String imgPath = emp.getPhoto_ID();
            System.out.println(imgPath);
          
            if(!imgPath.equalsIgnoreCase("") && imgPath.length() > 0){
                
            File file = new File(imgPath);
            BufferedImage bufferedImage = null;
            try {
                bufferedImage = ImageIO.read(file);
                bufferedImage = Common.resize(bufferedImage, 150, 150);
                //Image image = bufferedImage;
                ImageIcon imageIcon = new ImageIcon(bufferedImage);
                photo.setIcon(imageIcon);
                
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            }
            else
                photo.setText("No Photo");
            
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biodata_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gaurdian = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        emp_detail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        landmark = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dt_admission = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        post = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        loc = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mob2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(590, 800));

        biodata_panel.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setText("Name");

        name.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        name.setText("Arup");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Gaurdian's Name");

        gaurdian.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        gaurdian.setText("Arup");

        emp_detail.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        emp_detail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emp_detail.setText("Employee Details");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("Address");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Age.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        Age.setText("Age");
        Age.setToolTipText("");
        Age.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Mob no 1.");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        age.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        age.setText("30");
        age.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        mobile.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        mobile.setText("9903012949 ");
        mobile.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        address.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        address.setText("Tollygunge");
        address.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        landmark.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        landmark.setText("Kolkata-700040");
        landmark.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel7.setText("Date of Adm.");

        dt_admission.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        dt_admission.setText("13th may,2013");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel9.setText("Post");

        post.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        post.setText("12 Hrs Ayaah");

        photo.setBackground(new java.awt.Color(1, 1, 1));
        photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        photo.setMaximumSize(new java.awt.Dimension(24, 17));
        photo.setMinimumSize(new java.awt.Dimension(24, 17));
        photo.setPreferredSize(new java.awt.Dimension(24, 17));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel5.setText("How to go");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel6.setText("N.B : This is computarised datails of this employee which is given for date of admission");

        loc.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        loc.setText("Land Mark");
        loc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        location.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        location.setText("Kolkata ");
        location.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel8.setText("Mob no 2.");

        mob2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        mob2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mob2.setText("3333/2222/");
        mob2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout biodata_panelLayout = new javax.swing.GroupLayout(biodata_panel);
        biodata_panel.setLayout(biodata_panelLayout);
        biodata_panelLayout.setHorizontalGroup(
            biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodata_panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(biodata_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, biodata_panelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gaurdian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, biodata_panelLayout.createSequentialGroup()
                                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mob2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(biodata_panelLayout.createSequentialGroup()
                                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dt_admission, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(35, 35, 35))
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(biodata_panelLayout.createSequentialGroup()
                                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(landmark, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(biodata_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        biodata_panelLayout.setVerticalGroup(
            biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodata_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(emp_detail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(biodata_panelLayout.createSequentialGroup()
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gaurdian, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(mob2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dt_admission)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biodata_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landmark, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(biodata_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(biodata_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JPanel biodata_panel;
    private javax.swing.JLabel dt_admission;
    private javax.swing.JLabel emp_detail;
    private javax.swing.JLabel gaurdian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel landmark;
    private javax.swing.JLabel loc;
    private javax.swing.JLabel location;
    private javax.swing.JLabel mob2;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel post;
    // End of variables declaration//GEN-END:variables
}
